#pragma once

#include <vector>
#include <string>

using namespace std;

const vector<string> WORD_LIST = {
    "CRANE","SLATE","AUDIO","HOUSE","PLANT","SUGAR","TIGER","FLAME","BLOOD","STORM",
    "BRICK","LIGHT","NIGHT","CHESS","PIXEL","MOUSE","GLOBE","CROWN","DREAM","FROST",
    "GRIND","SHARK","BLAST","SWIFT","CRISP","FLUTE","GRAPE","KNEEL","MOURN","ORBIT",
    "PORCH","SCOUT","THUMP","VAPOR","WASTE","YACHT","BRIDE","CHOIR","DEPOT","ELBOW",
    "FEAST","GUAVA","CLAIM","BLANK","STOVE","TROUT","PLANK","CHANT","DRONE","SPIRE",
    "BLAZE","CRIMP","DWARF","ENVOY","FJORD","GLYPH","HELIX","INFER","JOUST","KARMA",
    "LAPEL","MAXIM","NYMPH","OXIDE","PROXY","QUAFF","RAVEN","STOMP","TRAWL","UMBRA",
    "VIXEN","WALTZ","BOXER","CYNIC","DEBUT","EXPEL","FUDGE","GENRE","HOTLY","IRATE"
};
